/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lampada;

import connect.MySQLConnectLamp;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Angelica
 */
public class Lampada extends javax.swing.JFrame {

    /**
     * Creates new form Lampada
     */
    
    
    
    public Lampada() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOnOff = new javax.swing.JToggleButton();
        lblLamp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(280, 292));
        setMinimumSize(new java.awt.Dimension(280, 292));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 302));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 302));
        jPanel1.setLayout(null);

        btnOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Off_132043.png"))); // NOI18N
        btnOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnOffActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnOff);
        btnOnOff.setBounds(110, 210, 49, 52);

        lblLamp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblLamp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apagada.png"))); // NOI18N
        jPanel1.add(lblLamp);
        lblLamp.setBounds(70, 30, 130, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnOffActionPerformed
        // TODO add your handling code here:
        
        try {
            MySQLConnectLamp con = new MySQLConnectLamp("localhost","lampada", "root", "");
            con.getMySQLConnect();
                
        if (btnOnOff.isSelected()){
            lblLamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/acesa.png")));
            btnOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/On.png")));
            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            
            String comando = "Update numcliques set ligar = ligar + 1 where id = 1";
            con.updateMySQL(comando);
            
        }else{
            lblLamp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apagada.png")));
            btnOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Off_132043.png")));
            jPanel1.setBackground(new java.awt.Color(0, 0, 0));
            
            String comando = "Update numcliques set desligar = desligar + 1 where id = 1";
            con.updateMySQL(comando);
        }
        
                
        String queryMysql = "select * from numcliques";
        String[][] resultQuery;
        resultQuery = con.queryMySQL(queryMysql);
        
        for(int i = 0; i<resultQuery.length; i++){
            for (int j=0; j<resultQuery[i].length; j++){
                System.out.print(resultQuery[i][j] + " | ");
            }
            System.out.println("");
        }
        
        con.closeConnection();
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro: " + e, "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnOnOffActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lampada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lampada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnOnOff;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLamp;
    // End of variables declaration//GEN-END:variables
}
